### ISSUE TITLE
Make the resend code button on verification code screen visible

### ISSUE THREAD

**Issue by Idadelveloper** [smswithoutborders/RelaySMS-Android#118]
The text appears to be black on a dark background which is practically invisible

**Comment by sherlockwisdom** [comment]
Would require parsing the counter sent from the Vault before the resend button should be visible - I'd complete this issue

**Comment by sherlockwisdom** [comment]
When the request is made, the Vault sends back a timestamp (in epoch time) when the next code would be available. The resend button must be deactivated till current_time == vault_reset_time. 

The user has to see a visible count down to the button becomes available (enabled)
